on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        php: [7.0, 7.1, 7.2, 7.3, 7.4, 8.0, 8.1]
    services:
      redis.0:
        ports:
          - 0:0
        args: --unixsocket /tmp/redis.sock
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3
      redis.6379:
        image: redis
        ports:
          - 6379:6379
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3
      redis.6380:
        image: redis
        ports:
          - 6380:6380
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3
      redis.6381:
        image: redis
        ports:
          - 6381:6381
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3
      redis.6382:
        image: redis
        ports:
          - 6382:6382
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: pecl :composer
          extensions: json, igbinary, msgpack

      - name: Install dependencies
        run: sudo apt-get install pkg-config libzstd1-dev liblz4-dev

      - name: Configure and build
        run: |
          phpize
          ./configure --enable-redis-lzf --enable-redis-zstd --enable-redis-lz4 --with-liblz4 --enable-redis-igbinary --enable-redis-msgpack
          sudo make install

      - name: Run tests
        run: |
          php tests/TestRedis.php --class Redis
          php tests/TestRedis.php --class RedisArray
          php tests/TestRedis.php --class RedisCluster
          php tests/TestRedis.php --class RedisSentinel
